package org.altruistas.backend_biblioteca.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Getter;

@Builder
@Getter
@DynamoDBTable(tableName = "libros")
public class Libro {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String isbn13;
    @DynamoDBAttribute
    private String isbn10;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String subtitle;
    @DynamoDBAttribute
    private String authors;
    @DynamoDBAttribute
    private String categories;
    @DynamoDBAttribute
    private String thumbnail;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute(attributeName = "published_year")
    private Integer publishedYear;
    @DynamoDBAttribute(attributeName = "average_rating")
    private Double averageRating;
}
