amazon:
  aws:
    accesskey: 'pyhwwe'
    secretkey: '2d3pi5'
  dynamodb:
    endpoint: 'http://localhost:8000'
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
